runtime: nodejs16 # or another supported version

instance_class: F2

env_variables:
  JAWSDB_URL: "mysql://fp0zs5mqsr2qa9id:plnoy4bbvx64af95@eanl4i1omny740jw.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/zcippd51nr33sj9q"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto